package mario;

import java.awt.Canvas;

public class MarioLevel1 extends MarioGameLevel {
	
	public MarioLevel1(Canvas canvas) {
		super(canvas);
		AutoGenerateDecor decor = new AutoGenerateDecor();
		_levelMap = decor.getLevel1();
		_inside = false;
		_scrollable = true;
		_width = 154;
	}
}
