package mario;

import java.awt.Canvas;

public class MarioLevel2 extends MarioGameLevel {

	public MarioLevel2(Canvas canvas) {
		super(canvas);
		AutoGenerateDecor decor = new AutoGenerateDecor();
		_levelMap = decor.getLevel2();
		_inside = true;
		_scrollable = false;
		_width = 26;
	}

}
